version: '2'
services:
  pwnboard:
    build:
      context: .
    #ports:
    #  - "5000:5000"
    links:
      - redis
    depends_on:
      - "redis"
    container_name: pwnboard 
  redis:
    image: redis:latest
    container_name: redis
  nginx:
    build:
      context: ./docker/nginx
    ports:
    - "443:443"
    depends_on:
      - "pwnboard"
    container_name: nginx
